site_name: Vesvai Documentation
site_url: https://docs.vesv.ai.org/
site_description: Vesvai - Coding Agent Documentation

repo_name: vesvai/vesvai
repo_url: https://github.com/vesvai/vesvai
edit_uri: https://github.com/vesvai/docs/edit/master/docs/

copyright: "&copy; 2026 Vesvai"

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: lucide/sun-moon
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: lucide/sun
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: lucide/moon-star
        name: Switch to system preference
  icon:
    tag:
      default: lucide/hash

plugins:
  - search
  - tags
  - markdown-exec

extra:
  homepage: https://vesv.ai
  scope: /
  annotate:
    json: [.s2]
  status:
    new: Recently added
    deprecated: Deprecated
    material: Material for MkDocs
  social:
  tags:
    default: default

extra_css:
  - style.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - zensical.extensions.glightbox:
      auto_themed: true
  - zensical.extensions.preview:
      targets:
        include:
          - customization.md
          - compatibility/markdown/*
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:zensical.extensions.emoji.to_svg
      emoji_index: !!python/name:zensical.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: zensical
      repo: zensical
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: https://vesv.ai
  - Vesvai:
      - Overview: vesvai/overview.md
      - Installation: vesvai/installation.md
      - Providers & Models: vesvai/providers-and-models.md
      - Config: vesvai/config.md
      - Troubleshooting: vesvai/troubleshooting.md
      - Usage:
        - CLI: vesvai/usage/cli.md
        - TUI: vesvai/usage/tui.md
        - HTTP: vesvai/usage/http.md
        - ACP: vesvai/usage/acp.md
      - Configurations:
        - Tools: vesvai/configurations/tools.md
        - Skills: vesvai/configurations/skills.md
        - Rules: vesvai/configurations/rules.md
        - MCP: vesvai/configurations/mcp.md
        - LSP: vesvai/configurations/lsp.md
      - Features:
        - Subagents: vesvai/features/subagents.md
        - Commands: vesvai/features/commands.md
        - Adding Context: vesvai/features/adding-context.md
        - Sessions: vesvai/features/sessions.md
        - Permissions: vesvai/features/permissions.md
  - Sdk:
      - Get Started: sdk/index.md
      - Chat: sdk/chat.md
      - Sessions: sdk/sessions.md
      - Files: sdk/files.md
      - Extending: sdk/extending.md
      - Events & Errors: sdk/events-errors.md