package all

import (
	"github.com/vesvai/vesvai/internal/hook"
	"github.com/vesvai/vesvai/internal/llm/providers/azure"
	"github.com/vesvai/vesvai/internal/llm/providers/cerebras"
	"github.com/vesvai/vesvai/internal/llm/providers/cloudflare"
	"github.com/vesvai/vesvai/internal/llm/providers/dashscope"
	"github.com/vesvai/vesvai/internal/llm/providers/deepinfra"
	"github.com/vesvai/vesvai/internal/llm/providers/deepseek"
	"github.com/vesvai/vesvai/internal/llm/providers/featherless"
	"github.com/vesvai/vesvai/internal/llm/providers/fireworks"
	"github.com/vesvai/vesvai/internal/llm/providers/friendliai"
	"github.com/vesvai/vesvai/internal/llm/providers/gaudi"
	"github.com/vesvai/vesvai/internal/llm/providers/gemini"
	"github.com/vesvai/vesvai/internal/llm/providers/github"
	"github.com/vesvai/vesvai/internal/llm/providers/groq"
	"github.com/vesvai/vesvai/internal/llm/providers/huggingface"
	"github.com/vesvai/vesvai/internal/llm/providers/hunyuan"
	"github.com/vesvai/vesvai/internal/llm/providers/hyperbolic"
	"github.com/vesvai/vesvai/internal/llm/providers/lambdalabs"
	"github.com/vesvai/vesvai/internal/llm/providers/lepton"
	"github.com/vesvai/vesvai/internal/llm/providers/lmstudio"
	"github.com/vesvai/vesvai/internal/llm/providers/localai"
	"github.com/vesvai/vesvai/internal/llm/providers/mistral"
	"github.com/vesvai/vesvai/internal/llm/providers/moonshot"
	"github.com/vesvai/vesvai/internal/llm/providers/novita"
	"github.com/vesvai/vesvai/internal/llm/providers/nvidia"
	"github.com/vesvai/vesvai/internal/llm/providers/ollama"
	"github.com/vesvai/vesvai/internal/llm/providers/opencode"
	"github.com/vesvai/vesvai/internal/llm/providers/openai"
	"github.com/vesvai/vesvai/internal/llm/providers/openrouter"
	"github.com/vesvai/vesvai/internal/llm/providers/perplexity"
	"github.com/vesvai/vesvai/internal/llm/providers/qianfan"
	"github.com/vesvai/vesvai/internal/llm/providers/sambanova"
	"github.com/vesvai/vesvai/internal/llm/providers/siliconflow"
	"github.com/vesvai/vesvai/internal/llm/providers/tgi"
	"github.com/vesvai/vesvai/internal/llm/providers/together"
	"github.com/vesvai/vesvai/internal/llm/providers/vertex"
	"github.com/vesvai/vesvai/internal/llm/providers/vllm"
	"github.com/vesvai/vesvai/internal/llm/providers/volcengine"
	"github.com/vesvai/vesvai/internal/llm/providers/watsonx"
	"github.com/vesvai/vesvai/internal/llm/providers/xai"
	"github.com/vesvai/vesvai/internal/llm/providers/zen"
	"github.com/vesvai/vesvai/internal/llm/providers/zhipu"
)

func RegisterAll(hooks *hook.Hooks) {
	azure.RegisterHooks(hooks)
	cerebras.RegisterHooks(hooks)
	cloudflare.RegisterHooks(hooks)
	dashscope.RegisterHooks(hooks)
	deepinfra.RegisterHooks(hooks)
	deepseek.RegisterHooks(hooks)
	featherless.RegisterHooks(hooks)
	fireworks.RegisterHooks(hooks)
	friendliai.RegisterHooks(hooks)
	gaudi.RegisterHooks(hooks)
	gemini.RegisterHooks(hooks)
	github.RegisterHooks(hooks)
	groq.RegisterHooks(hooks)
	huggingface.RegisterHooks(hooks)
	hunyuan.RegisterHooks(hooks)
	hyperbolic.RegisterHooks(hooks)
	lambdalabs.RegisterHooks(hooks)
	lepton.RegisterHooks(hooks)
	lmstudio.RegisterHooks(hooks)
	localai.RegisterHooks(hooks)
	mistral.RegisterHooks(hooks)
	moonshot.RegisterHooks(hooks)
	novita.RegisterHooks(hooks)
	nvidia.RegisterHooks(hooks)
	ollama.RegisterHooks(hooks)
	opencode.RegisterHooks(hooks)
	openai.RegisterHooks(hooks)
	openrouter.RegisterHooks(hooks)
	perplexity.RegisterHooks(hooks)
	qianfan.RegisterHooks(hooks)
	sambanova.RegisterHooks(hooks)
	siliconflow.RegisterHooks(hooks)
	tgi.RegisterHooks(hooks)
	together.RegisterHooks(hooks)
	vertex.RegisterHooks(hooks)
	vllm.RegisterHooks(hooks)
	volcengine.RegisterHooks(hooks)
	watsonx.RegisterHooks(hooks)
	xai.RegisterHooks(hooks)
	zen.RegisterHooks(hooks)
	zhipu.RegisterHooks(hooks)
}
