name: CI

permissions:
  contents: write

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'

      - name: Run tests
        run: go test -v ./...

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'

      - name: Auto-format
        run: gofmt -w .

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: fix code style"
          commit_options: "--no-verify"

  vet:
    name: Vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'

      - name: Run go vet
        run: go vet ./...
